name: Publish GitHub Release Artifacts
description: |
  This action publishes files from GitHub Actions as artifacts on a GitHub release.
  It is intended to be run within a `release` workflow, however can also be executed
  within a `push` workflow if required.
author: Sierra Softworks
inputs:
  token:
    required: true
    description: |
      The GitHub access token which will be used to upload release artifacts.

      Usually this will be `${{ secrets.GITHUB_TOKEN }}`.

  files:
    required: true
    description: |
      A list of files to publish, relative to the repository root.

      The files must be specified as a newline-delimited list of paths.

      ```yaml
      with:
        files: |
          - bin/release-windows
          - bin/release-linux
      ```

  release_tag:
    required: false
    description: |
      The release tag which should receive the artifacts.
      
      By default this will be discovered based on the build environment, however
      you may specify it here if automatic discovery does not work for your usecase.

runs:
  using: 'node16'
  main: 'dist/index.js'
